const mongoose = require('mongoose');
require('dotenv').config(); 
const Question = require('./models/Question');

mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log('MongoDB Connected for New DI Tables Seeding'))
  .catch(err => console.log(err));

const batch19Questions = [
    // ==========================================
    // DI SET 1 - MANUFACTURING SALES
    // ==========================================
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 1: Manufacturing Sales**\n\nA company manufactures 6 products over a year. (Note: Units are in thousands)\n\n| Product | Units Sold (in 000s) | Cost/Unit (₹) | Selling Price/Unit (₹) |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 80 | 110 |\n| **B** | 150 | 70 | 100 |\n| **C** | 180 | 60 | 95 |\n| **D** | 200 | 50 | 75 |\n| **E** | 140 | 90 | 130 |\n| **F** | 110 | 100 | 150 |\n\n**Q1.** Find the total revenue generated by all products.",
        options: ["₹8.50 Crore", "₹9.10 Crore", "₹9.50 Crore", "₹10.20 Crore"],
        correctAnswer: "₹9.50 Crore",
        explanation: "Step 1: Revenue = Units Sold * Selling Price.\nStep 2: Calculate for each (in thousands):\nA: 120 * 110 = 13,200\nB: 150 * 100 = 15,000\nC: 180 * 95 = 17,100\nD: 200 * 75 = 15,000\nE: 140 * 130 = 18,200\nF: 110 * 150 = 16,500\nStep 3: Total = 95,000 thousands = 95,000,000 = ₹9.50 Crores."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 1: Manufacturing Sales**\n\n| Product | Units Sold (in 000s) | Cost/Unit (₹) | Selling Price/Unit (₹) |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 80 | 110 |\n| **B** | 150 | 70 | 100 |\n| **C** | 180 | 60 | 95 |\n| **D** | 200 | 50 | 75 |\n| **E** | 140 | 90 | 130 |\n| **F** | 110 | 100 | 150 |\n\n**Q2.** Find the total profit earned by the company.",
        options: ["₹2.85 Crore", "₹3.05 Crore", "₹3.20 Crore", "₹3.50 Crore"],
        correctAnswer: "₹3.05 Crore",
        explanation: "Step 1: Profit per unit = SP - Cost.\nStep 2: Profits per unit -> A:30, B:30, C:35, D:25, E:40, F:50.\nStep 3: Total Profit (in thousands) = (120*30) + (150*30) + (180*35) + (200*25) + (140*40) + (110*50).\nStep 4: 3600 + 4500 + 6300 + 5000 + 5600 + 5500 = 30,500 thousands = ₹3.05 Crore."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 1: Manufacturing Sales**\n\n| Product | Units Sold (in 000s) | Cost/Unit (₹) | Selling Price/Unit (₹) |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 80 | 110 |\n| **B** | 150 | 70 | 100 |\n| **C** | 180 | 60 | 95 |\n| **D** | 200 | 50 | 75 |\n| **E** | 140 | 90 | 130 |\n| **F** | 110 | 100 | 150 |\n\n**Q3.** Which product contributes the highest profit?",
        options: ["Product C", "Product D", "Product E", "Product F"],
        correctAnswer: "Product C",
        explanation: "Step 1: Refer to total profits calculated.\nA: 3600, B: 4500, C: 6300, D: 5000, E: 5600, F: 5500 (in thousands).\nStep 2: The highest profit is 6300 (₹63 Lakhs), generated by Product C."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 1: Manufacturing Sales**\n\n| Product | Units Sold (in 000s) | Cost/Unit (₹) | Selling Price/Unit (₹) |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 80 | 110 |\n| **B** | 150 | 70 | 100 |\n| **C** | 180 | 60 | 95 |\n| **D** | 200 | 50 | 75 |\n| **E** | 140 | 90 | 130 |\n| **F** | 110 | 100 | 150 |\n\n**Q4.** Find the percentage contribution of Product C to total revenue.",
        options: ["15%", "18%", "20%", "22%"],
        correctAnswer: "18%",
        explanation: "Step 1: Revenue of Product C = 180k * ₹95 = ₹1,71,00,000 (1.71 Cr).\nStep 2: Total Revenue = ₹9,50,00,000 (9.5 Cr).\nStep 3: Percentage = (1.71 / 9.5) * 100 = 18%."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 1: Manufacturing Sales**\n\n| Product | Units Sold (in 000s) | Cost/Unit (₹) | Selling Price/Unit (₹) |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 80 | 110 |\n| **B** | 150 | 70 | 100 |\n| **C** | 180 | 60 | 95 |\n| **D** | 200 | 50 | 75 |\n| **E** | 140 | 90 | 130 |\n| **F** | 110 | 100 | 150 |\n\n**Q5.** If sales of Product F increase by 20%, what will be the new total profit?",
        options: ["₹3.10 Crore", "₹3.16 Crore", "₹3.25 Crore", "₹3.30 Crore"],
        correctAnswer: "₹3.16 Crore",
        explanation: "Step 1: Current total profit = ₹3.05 Crore.\nStep 2: Current profit from F = 110k * ₹50 = ₹55 Lakhs.\nStep 3: 20% increase in sales = 20% increase in profit = 20% of 55 = ₹11 Lakhs.\nStep 4: New total profit = 3.05 Cr + 0.11 Cr = ₹3.16 Crore."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Hard",
        questionText: "**DI Set 1: Manufacturing Sales**\n\n| Product | Units Sold (in 000s) | Cost/Unit (₹) | Selling Price/Unit (₹) |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 80 | 110 |\n| **B** | 150 | 70 | 100 |\n| **C** | 180 | 60 | 95 |\n| **D** | 200 | 50 | 75 |\n| **E** | 140 | 90 | 130 |\n| **F** | 110 | 100 | 150 |\n\n**Q6.** By what percentage should Product D's sales increase so that its profit equals Product E's profit?",
        options: ["10%", "12%", "15%", "18%"],
        correctAnswer: "12%",
        explanation: "Step 1: Current Profit of D = 200k * 25 = ₹50 Lakhs.\nStep 2: Profit of E = 140k * 40 = ₹56 Lakhs.\nStep 3: D needs to increase profit by 6 Lakhs to match E (56 - 50).\nStep 4: Percentage increase = (6 / 50) * 100 = 12%."
    },

    // ==========================================
    // DI SET 2 - EMPLOYEE DISTRIBUTION
    // ==========================================
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 2: Employee Distribution**\n\nEmployee distribution in a multinational company.\n\n| Department | Male | Female |\n|:---:|:---:|:---:|\n| **HR** | 120 | 80 |\n| **Finance** | 150 | 130 |\n| **IT** | 300 | 220 |\n| **Sales** | 250 | 170 |\n| **Operations** | 180 | 140 |\n\n**Q7.** Find the total number of employees in the company.",
        options: ["1680", "1700", "1740", "1800"],
        correctAnswer: "1740",
        explanation: "Step 1: Total Males = 120 + 150 + 300 + 250 + 180 = 1000.\nStep 2: Total Females = 80 + 130 + 220 + 170 + 140 = 740.\nStep 3: Total Employees = 1000 + 740 = 1740."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 2: Employee Distribution**\n\n| Department | Male | Female |\n|:---:|:---:|:---:|\n| **HR** | 120 | 80 |\n| **Finance** | 150 | 130 |\n| **IT** | 300 | 220 |\n| **Sales** | 250 | 170 |\n| **Operations** | 180 | 140 |\n\n**Q8.** What percentage of total employees belong to IT?",
        options: ["27.5%", "29.88%", "31.2%", "33.3%"],
        correctAnswer: "29.88%",
        explanation: "Step 1: IT Employees = 300 (M) + 220 (F) = 520.\nStep 2: Total Employees = 1740.\nStep 3: Percentage = (520 / 1740) * 100 ≈ 29.88%."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 2: Employee Distribution**\n\n| Department | Male | Female |\n|:---:|:---:|:---:|\n| **HR** | 120 | 80 |\n| **Finance** | 150 | 130 |\n| **IT** | 300 | 220 |\n| **Sales** | 250 | 170 |\n| **Operations** | 180 | 140 |\n\n**Q9.** Find the Male to Female ratio in the company.",
        options: ["25:18", "40:33", "50:37", "55:42"],
        correctAnswer: "50:37",
        explanation: "Step 1: Total Males = 1000.\nStep 2: Total Females = 740.\nStep 3: Ratio = 1000 : 740. Divide both by 20 => 50 : 37."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 2: Employee Distribution**\n\n| Department | Male | Female |\n|:---:|:---:|:---:|\n| **HR** | 120 | 80 |\n| **Finance** | 150 | 130 |\n| **IT** | 300 | 220 |\n| **Sales** | 250 | 170 |\n| **Operations** | 180 | 140 |\n\n**Q10.** If female employees increase by roughly 25% in Finance, what is the new total workforce?",
        options: ["1760", "1773", "1785", "1800"],
        correctAnswer: "1773",
        explanation: "Step 1: Current Females in Finance = 130.\nStep 2: 25% increase = 0.25 * 130 = 32.5 (approx 33 employees).\nStep 3: Old total = 1740. New total = 1740 + 33 = 1773."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 2: Employee Distribution**\n\n| Department | Male | Female |\n|:---:|:---:|:---:|\n| **HR** | 120 | 80 |\n| **Finance** | 150 | 130 |\n| **IT** | 300 | 220 |\n| **Sales** | 250 | 170 |\n| **Operations** | 180 | 140 |\n\n**Q11.** Which department has the highest percentage of female employees within its own workforce?",
        options: ["HR", "Finance", "IT", "Operations"],
        correctAnswer: "Finance",
        explanation: "Step 1: HR = 80/200 (40%).\nStep 2: Finance = 130/280 ≈ 46.4%.\nStep 3: IT = 220/520 ≈ 42.3%.\nStep 4: Sales = 170/420 ≈ 40.4%.\nStep 5: Operations = 140/320 ≈ 43.7%. Finance has the highest."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Hard",
        questionText: "**DI Set 2: Employee Distribution**\n\n| Department | Male | Female |\n|:---:|:---:|:---:|\n| **HR** | 120 | 80 |\n| **Finance** | 150 | 130 |\n| **IT** | 300 | 220 |\n| **Sales** | 250 | 170 |\n| **Operations** | 180 | 140 |\n\n**Q12.** How many additional males are required in HR to make the male:female ratio exactly 2:1?",
        options: ["30", "40", "50", "60"],
        correctAnswer: "40",
        explanation: "Step 1: Current females in HR = 80.\nStep 2: For a 2:1 ratio, required males = 80 * 2 = 160.\nStep 3: Current males in HR = 120.\nStep 4: Additional males needed = 160 - 120 = 40."
    },

    // ==========================================
    // DI SET 3 - ANNUAL REVENUE
    // ==========================================
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 3: Annual Revenue**\n\nAnnual revenue of 5 companies (in ₹ Crore).\n\n| Company | 2021 | 2022 | 2023 |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 150 | 210 |\n| **B** | 180 | 220 | 260 |\n| **C** | 140 | 170 | 250 |\n| **D** | 200 | 260 | 320 |\n| **E** | 160 | 210 | 280 |\n\n**Q13.** Which company/companies recorded the maximum absolute growth from 2021 to 2023?",
        options: ["Company C", "Company D", "Both D and E", "Company B"],
        correctAnswer: "Both D and E",
        explanation: "Step 1: Absolute growth = 2023 Revenue - 2021 Revenue.\nStep 2: A: 210-120=90. B: 260-180=80. C: 250-140=110.\nStep 3: D: 320-200=120. E: 280-160=120.\nStep 4: Both D and E show the maximum growth of 120 Cr."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 3: Annual Revenue**\n\n| Company | 2021 | 2022 | 2023 |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 150 | 210 |\n| **B** | 180 | 220 | 260 |\n| **C** | 140 | 170 | 250 |\n| **D** | 200 | 260 | 320 |\n| **E** | 160 | 210 | 280 |\n\n**Q14.** Find the average annual revenue of Company D across the three years.",
        options: ["240 Cr", "250 Cr", "260 Cr", "280 Cr"],
        correctAnswer: "260 Cr",
        explanation: "Step 1: Total revenue of D = 200 + 260 + 320 = 780 Cr.\nStep 2: Number of years = 3.\nStep 3: Average = 780 / 3 = 260 Cr."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 3: Annual Revenue**\n\n| Company | 2021 | 2022 | 2023 |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 150 | 210 |\n| **B** | 180 | 220 | 260 |\n| **C** | 140 | 170 | 250 |\n| **D** | 200 | 260 | 320 |\n| **E** | 160 | 210 | 280 |\n\n**Q15.** What percentage of the total 2023 revenue comes from Company E?",
        options: ["18.5%", "19.2%", "21.21%", "23.5%"],
        correctAnswer: "21.21%",
        explanation: "Step 1: Total 2023 revenue = 210 + 260 + 250 + 320 + 280 = 1320 Cr.\nStep 2: Company E revenue in 2023 = 280 Cr.\nStep 3: Percentage = (280 / 1320) * 100 ≈ 21.21%."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 3: Annual Revenue**\n\n| Company | 2021 | 2022 | 2023 |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 150 | 210 |\n| **B** | 180 | 220 | 260 |\n| **C** | 140 | 170 | 250 |\n| **D** | 200 | 260 | 320 |\n| **E** | 160 | 210 | 280 |\n\n**Q16.** If Company B grows by another 15% in the next year, estimate its 2024 revenue.",
        options: ["290 Cr", "295 Cr", "299 Cr", "305 Cr"],
        correctAnswer: "299 Cr",
        explanation: "Step 1: Company B's 2023 revenue = 260 Cr.\nStep 2: 15% of 260 = 0.15 * 260 = 39 Cr.\nStep 3: 2024 Revenue = 260 + 39 = 299 Cr."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 3: Annual Revenue**\n\n| Company | 2021 | 2022 | 2023 |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 150 | 210 |\n| **B** | 180 | 220 | 260 |\n| **C** | 140 | 170 | 250 |\n| **D** | 200 | 260 | 320 |\n| **E** | 160 | 210 | 280 |\n\n**Q17.** Find the ratio of the combined revenues of A and C in 2023 to D and E in 2023.",
        options: ["19:25", "23:30", "25:31", "21:28"],
        correctAnswer: "23:30",
        explanation: "Step 1: Combined (A + C) in 2023 = 210 + 250 = 460.\nStep 2: Combined (D + E) in 2023 = 320 + 280 = 600.\nStep 3: Ratio = 460 : 600. Divide by 20 => 23 : 30."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Hard",
        questionText: "**DI Set 3: Annual Revenue**\n\n| Company | 2021 | 2022 | 2023 |\n|:---:|:---:|:---:|:---:|\n| **A** | 120 | 150 | 210 |\n| **B** | 180 | 220 | 260 |\n| **C** | 140 | 170 | 250 |\n| **D** | 200 | 260 | 320 |\n| **E** | 160 | 210 | 280 |\n\n**Q18.** Find the absolute overall growth percentage of Company A from 2021 to 2023.",
        options: ["50%", "65%", "75%", "90%"],
        correctAnswer: "75%",
        explanation: "Step 1: Initial (2021) = 120. Final (2023) = 210.\nStep 2: Increase = 210 - 120 = 90.\nStep 3: Growth % = (90 / 120) * 100 = 0.75 * 100 = 75%."
    },

    // ==========================================
    // DI SET 4 - CAMPUS PLACEMENTS
    // ==========================================
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 4: Campus Placements**\n\n| Company | Students Selected |\n|:---:|:---:|\n| **TCS** | 140 |\n| **Infosys** | 110 |\n| **Accenture** | 95 |\n| **Capgemini** | 125 |\n| **Cognizant** | 90 |\n| **Deloitte** | 70 |\n\n**Q19.** Find the total number of campus placements.",
        options: ["580", "600", "630", "650"],
        correctAnswer: "630",
        explanation: "Step 1: Simply sum up the values.\nStep 2: 140 + 110 + 95 + 125 + 90 + 70 = 630 students."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 4: Campus Placements**\n\n| Company | Students Selected |\n|:---:|:---:|\n| **TCS** | 140 |\n| **Infosys** | 110 |\n| **Accenture** | 95 |\n| **Capgemini** | 125 |\n| **Cognizant** | 90 |\n| **Deloitte** | 70 |\n\n**Q20.** Find the percentage of students selected by service-based companies (TCS, Infosys, Cognizant, and Capgemini).",
        options: ["70.5%", "73.8%", "75.2%", "78.4%"],
        correctAnswer: "73.8%",
        explanation: "Step 1: Sum of TCS, Infosys, Cognizant, Capgemini = 140 + 110 + 90 + 125 = 465.\nStep 2: Total selections = 630.\nStep 3: Percentage = (465 / 630) * 100 ≈ 73.8%."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 4: Campus Placements**\n\n| Company | Students Selected |\n|:---:|:---:|\n| **TCS** | 140 |\n| **Infosys** | 110 |\n| **Accenture** | 95 |\n| **Capgemini** | 125 |\n| **Cognizant** | 90 |\n| **Deloitte** | 70 |\n\n**Q21.** If Deloitte doubles its hiring, what will be the new total placement count?",
        options: ["680", "700", "720", "740"],
        correctAnswer: "700",
        explanation: "Step 1: Deloitte currently hires 70.\nStep 2: Double hiring means adding another 70 students.\nStep 3: New Total = 630 + 70 = 700."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 4: Campus Placements**\n\n| Company | Students Selected |\n|:---:|:---:|\n| **TCS** | 140 |\n| **Infosys** | 110 |\n| **Accenture** | 95 |\n| **Capgemini** | 125 |\n| **Cognizant** | 90 |\n| **Deloitte** | 70 |\n\n**Q22.** Find the ratio of TCS selections to Accenture selections.",
        options: ["25:17", "28:19", "30:19", "28:17"],
        correctAnswer: "28:19",
        explanation: "Step 1: TCS = 140. Accenture = 95.\nStep 2: Ratio = 140 : 95. Divide both by 5.\nStep 3: 28 : 19."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 4: Campus Placements**\n\n| Company | Students Selected |\n|:---:|:---:|\n| **TCS** | 140 |\n| **Infosys** | 110 |\n| **Accenture** | 95 |\n| **Capgemini** | 125 |\n| **Cognizant** | 90 |\n| **Deloitte** | 70 |\n\n**Q23.** Which company contributes the least percentage to the total pool?",
        options: ["Accenture", "Infosys", "Cognizant", "Deloitte"],
        correctAnswer: "Deloitte",
        explanation: "Step 1: The least percentage directly correlates to the lowest absolute count.\nStep 2: Deloitte has the lowest selections at 70."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 4: Campus Placements**\n\n| Company | Students Selected |\n|:---:|:---:|\n| **TCS** | 140 |\n| **Infosys** | 110 |\n| **Accenture** | 95 |\n| **Capgemini** | 125 |\n| **Cognizant** | 90 |\n| **Deloitte** | 70 |\n\n**Q24.** How many more students must Cognizant hire to match Capgemini's numbers?",
        options: ["25", "30", "35", "40"],
        correctAnswer: "35",
        explanation: "Step 1: Capgemini selections = 125.\nStep 2: Cognizant selections = 90.\nStep 3: Difference = 125 - 90 = 35 students."
    },

    // ==========================================
    // DI SET 5 - LOGISTICS & REVENUE (ZS LEVEL)
    // ==========================================
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 5: Logistics Analytics**\n\nA logistics company reports monthly shipments.\n\n| Month | Domestic | International |\n|:---:|:---:|:---:|\n| **Jan** | 250 | 120 |\n| **Feb** | 280 | 150 |\n| **Mar** | 300 | 170 |\n| **Apr** | 340 | 180 |\n| **May** | 390 | 220 |\n\n**Q25.** Find total shipments over all months.",
        options: ["2200", "2350", "2400", "2500"],
        correctAnswer: "2400",
        explanation: "Step 1: Total Domestic = 250+280+300+340+390 = 1560.\nStep 2: Total International = 120+150+170+180+220 = 840.\nStep 3: Total shipments = 1560 + 840 = 2400."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 5: Logistics Analytics**\n\n| Month | Domestic | International |\n|:---:|:---:|:---:|\n| **Jan** | 250 | 120 |\n| **Feb** | 280 | 150 |\n| **Mar** | 300 | 170 |\n| **Apr** | 340 | 180 |\n| **May** | 390 | 220 |\n\n**Q26.** Find the percentage increase in Domestic shipments from Jan to May.",
        options: ["45%", "50%", "56%", "62%"],
        correctAnswer: "56%",
        explanation: "Step 1: Jan Domestic = 250. May Domestic = 390.\nStep 2: Increase = 390 - 250 = 140.\nStep 3: Percentage = (140 / 250) * 100 = 56%."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Easy",
        questionText: "**DI Set 5: Logistics Analytics**\n\n| Month | Domestic | International |\n|:---:|:---:|:---:|\n| **Jan** | 250 | 120 |\n| **Feb** | 280 | 150 |\n| **Mar** | 300 | 170 |\n| **Apr** | 340 | 180 |\n| **May** | 390 | 220 |\n\n**Q27.** Find average International shipments.",
        options: ["150", "168", "175", "180"],
        correctAnswer: "168",
        explanation: "Step 1: Total International = 840.\nStep 2: Months = 5.\nStep 3: Average = 840 / 5 = 168."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Medium",
        questionText: "**DI Set 5: Logistics Analytics**\n\n| Month | Domestic | International |\n|:---:|:---:|:---:|\n| **Jan** | 250 | 120 |\n| **Feb** | 280 | 150 |\n| **Mar** | 300 | 170 |\n| **Apr** | 340 | 180 |\n| **May** | 390 | 220 |\n\n**Q28.** In which month was the gap between Domestic and International shipments highest?",
        options: ["Feb", "Mar", "Apr", "May"],
        correctAnswer: "May",
        explanation: "Step 1: Gap = Domestic - International.\nJan = 130, Feb = 130, Mar = 130, Apr = 160, May = 170.\nStep 2: The gap was highest in May (170)."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Hard",
        questionText: "**DI Set 5: Logistics Analytics**\n\n| Month | Domestic | International |\n|:---:|:---:|:---:|\n| **Jan** | 250 | 120 |\n| **Feb** | 280 | 150 |\n| **Mar** | 300 | 170 |\n| **Apr** | 340 | 180 |\n| **May** | 390 | 220 |\n\n**Q29.** If June shipments rise by the average monthly absolute increase observed in Domestic shipments, predict June's Domestic shipments.",
        options: ["410", "415", "425", "430"],
        correctAnswer: "425",
        explanation: "Step 1: Total absolute increase in Domestic from Jan to May = 390 - 250 = 140.\nStep 2: Number of intervals (jumps) = 4.\nStep 3: Average monthly increase = 140 / 4 = 35.\nStep 4: June prediction = May (390) + 35 = 425."
    },
    {
        category: "Data Interpretation", topic: "Tables & Caselets", difficulty: "Hard",
        questionText: "**DI Set 5: Logistics Analytics (Mu Sigma / ZS Level)**\n\nAssume revenue per shipment is as follows:\n- Domestic = ₹12,000\n- International = ₹25,000\n\n| Month | Domestic | International |\n|:---:|:---:|:---:|\n| **Jan** | 250 | 120 |\n| **Feb** | 280 | 150 |\n| **Mar** | 300 | 170 |\n| **Apr** | 340 | 180 |\n| **May** | 390 | 220 |\n\n**Q30.** Find the total revenue generated during the five months.",
        options: ["₹3.50 Crore", "₹3.85 Crore", "₹3.97 Crore", "₹4.10 Crore"],
        correctAnswer: "₹3.97 Crore",
        explanation: "Step 1: Total Domestic Shipments = 1560. Revenue = 1560 * 12,000 = ₹1,87,20,000.\nStep 2: Total International Shipments = 840. Revenue = 840 * 25,000 = ₹2,10,00,000.\nStep 3: Total Revenue = 1.872 Cr + 2.10 Cr = ₹3.972 Crore (Approx ₹3.97 Crore)."
    }
];

const seedBatch19DataInterpretation = async () => {
    try {
        console.log("🧹 ALERT: Deleting old Data Interpretation questions...");
        await Question.deleteMany({ topic: "Tables & Caselets" }); 
        console.log("🗑️ Purana Data safely deleted!");

        console.log(`🚀 Injecting ${batch19Questions.length} Fresh Data Interpretation Questions...`);
        
        await Question.insertMany(batch19Questions);
        console.log(`✅ BOOM! Tumhara naya DI Data (Batch 19) properly replace aur seed ho gaya hai!`);
        
        process.exit();
    } catch (error) {
        console.error("Error seeding data: ", error);
        process.exit(1);
    }
};

seedBatch19DataInterpretation();