const mongoose = require('mongoose');
require('dotenv').config(); 
const Question = require('./models/Question');

mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log('MongoDB Connected for Premium Mixed Graphs'))
  .catch(err => console.log(err));

// ==========================================
// DYNAMIC JSON CHARTS FOR 5 DIFFERENT SETS
// ==========================================
const set1Pie = `\n\`\`\`json\n{ "type": "pie", "data": [ {"name": "BFSI", "value": 30}, {"name": "Health", "value": 25}, {"name": "Retail", "value": 20}, {"name": "Telecom", "value": 15}, {"name": "Others", "value": 10} ] }\n\`\`\`\n`;
const set2Pie = `\n\`\`\`json\n{ "type": "pie", "data": [ {"name": "Elec", "value": 35}, {"name": "Fashion", "value": 25}, {"name": "Grocery", "value": 20}, {"name": "Home", "value": 15}, {"name": "Toys", "value": 5} ] }\n\`\`\`\n`;
const set3Line = `\n\`\`\`json\n{ "type": "line", "data": [ {"name": "North", "Employees": 800}, {"name": "South", "Employees": 600}, {"name": "East", "Employees": 500}, {"name": "West", "Employees": 600} ] }\n\`\`\`\n`;
const set4Pie = `\n\`\`\`json\n{ "type": "pie", "data": [ {"name": "Samsung", "value": 30}, {"name": "Apple", "value": 25}, {"name": "Xiaomi", "value": 20}, {"name": "OnePlus", "value": 15}, {"name": "Others", "value": 10} ] }\n\`\`\`\n`;
const set4Bar = `\n\`\`\`json\n{ "type": "bar", "data": [ {"name": "Samsung", "value": 40}, {"name": "Apple", "value": 90}, {"name": "Xiaomi", "value": 10}, {"name": "OnePlus", "value": 50}, {"name": "Others", "value": 5} ] }\n\`\`\`\n`;
const set5Line = `\n\`\`\`json\n{ "type": "line", "data": [ {"name": "2020", "Budget": 100}, {"name": "2021", "Budget": 150}, {"name": "2022", "Budget": 200}, {"name": "2023", "Budget": 250}, {"name": "2024", "Budget": 300} ] }\n\`\`\`\n`;

// ==========================================
// PASSAGES (5 DISTINCT SETS)
// ==========================================
const mixSet1 = `**Mixed DI Set 1: Corporate Performance (Table + Pie)**\n\n**Table: Annual Revenue Trend**\n| Year | Revenue (₹ Cr) |\n|---|---|\n| 2021 | 650 |\n| 2022 | 850 |\n| 2023 | 1100 |\n| 2024 | 1500 |\n\n**Pie Chart: 2024 Revenue Distribution (%)**${set1Pie}\n**Table: Profit Margin (2024)**\n| Segment | Margin % |\n|---|---|\n| BFSI | 22% |\n| Healthcare | 28% |\n| Retail | 18% |\n| Telecom | 25% |\n| Others | 12% |\n\n`;

const mixSet2 = `**Mixed DI Set 2: E-Commerce Analytics (Table + Pie)**\n\nA platform received exactly 80,000 orders in a month.\n\n**Pie Chart: Order Distribution (%)**${set2Pie}\n**Table: Delivery Success & Average Order Value (AOV)**\n| Category | Success Rate | AOV (₹) |\n|---|---|---|\n| Electronics | 90% | 2000 |\n| Fashion | 85% | 800 |\n| Grocery | 95% | 500 |\n| Home | 88% | 1500 |\n| Toys | 80% | 400 |\n\n`;

const mixSet3 = `**Mixed DI Set 3: Workforce Analytics (Table + Line)**\n\nA tech firm has 2,500 employees across 4 regions.\n\n**Line Graph: Total Employees per Region**${set3Line}\n**Table: IT Dept Allocation & Average Salary**\n| Region | % in IT Dept | Avg IT Salary (LPA) |\n|---|---|---|\n| North | 40% | ₹12 Lakhs |\n| South | 50% | ₹10 Lakhs |\n| East | 30% | ₹8 Lakhs |\n| West | 45% | ₹15 Lakhs |\n\n`;

const mixSet4 = `**Mixed DI Set 4: Smartphone Market Mix (Pie + Bar)**\n\nTotal smartphones sold in a quarter = 50 Lakh units.\n\n**Pie Chart: Brand Market Share (%)**${set4Pie}\n**Bar Graph: % of Premium Phones (>₹50k) Sold per Brand**${set4Bar}`;

const mixSet5 = `**Mixed DI Set 5: Marketing ROI (Table + Line)**\n\n**Line Graph: Total Marketing Budget (₹ Cr) over 5 Years**${set5Line}\n**Table: 2024 Budget Allocation & Customer Acquisition Cost (CAC)**\n| Channel | Allocation % | CAC (₹ per user) |\n|---|---|---|\n| Social Media | 40% | 500 |\n| Search Ads | 30% | 800 |\n| Email | 20% | 300 |\n| Offline | 10% | 2000 |\n\n`;

const batch27Questions = [
    // ================== SET 1 (Q1-Q6) ==================
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet1}**Q1.** Find the revenue (in ₹ Crore) generated by the Healthcare segment in 2024.`,
        options: ["₹350 Cr", "₹375 Cr", "₹400 Cr", "₹425 Cr"], correctAnswer: "₹375 Cr", explanation: "Healthcare share = 25%. Total Revenue 2024 = 1500 Cr. Revenue = 0.25 * 1500 = ₹375 Cr."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet1}**Q2.** Find the total profit generated by the company in 2024.`,
        options: ["₹312.5 Cr", "₹332.25 Cr", "₹345.5 Cr", "₹360.0 Cr"], correctAnswer: "₹332.25 Cr", explanation: "BFSI Profit: 450*0.22 = 99\nHC Profit: 375*0.28 = 105\nRetail Profit: 300*0.18 = 54\nTelecom Profit: 225*0.25 = 56.25\nOthers Profit: 150*0.12 = 18\nTotal = 332.25 Cr."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Easy",
        questionText: `${mixSet1}**Q3.** Which segment contributes the maximum absolute profit to the company?`,
        options: ["BFSI", "Healthcare", "Telecom", "Retail"], correctAnswer: "Healthcare", explanation: "Healthcare provides ₹105 Cr in profit, which is the highest."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet1}**Q4.** Find the ratio of BFSI profit to Retail profit.`,
        options: ["11:6", "9:5", "10:7", "12:5"], correctAnswer: "11:6", explanation: "BFSI Profit = 99 Cr. Retail Profit = 54 Cr. Ratio = 99/54 = 11:6."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet1}**Q5.** Predict the 2025 revenue if it grows by exactly the latest YoY growth rate (2023 to 2024).`,
        options: ["₹1950 Cr", "₹2000 Cr", "₹2045 Cr", "₹2150 Cr"], correctAnswer: "₹2045 Cr", explanation: "Growth 23-24 = (1500-1100)/1100 = 36.36%. 1500 * 1.3636 = ₹2045.4 Cr."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet1}**Q6.** If Retail margin improves by 5 percentage points (from 18% to 23%), what is the revised total company profit?`,
        options: ["₹340.50 Cr", "₹347.25 Cr", "₹352.00 Cr", "₹360.25 Cr"], correctAnswer: "₹347.25 Cr", explanation: "Retail revenue = 300 Cr. 5% extra margin = 15 Cr additional profit. New total = 332.25 + 15 = 347.25 Cr."
    },

    // ================== SET 2 (Q7-Q12) ==================
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet2}**Q7.** Find the number of successfully delivered Electronics orders.`,
        options: ["24,000", "25,200", "26,500", "28,000"], correctAnswer: "25,200", explanation: "Elec orders = 35% of 80,000 = 28,000. Success = 90%. Delivered = 28,000 * 0.90 = 25,200."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet2}**Q8.** Calculate the total revenue generated strictly from successful Fashion deliveries.`,
        options: ["₹1.15 Cr", "₹1.36 Cr", "₹1.50 Cr", "₹1.75 Cr"], correctAnswer: "₹1.36 Cr", explanation: "Fashion orders = 25% of 80k = 20,000. Success = 85% = 17,000. Revenue = 17,000 * ₹800 = ₹1,36,00,000 (1.36 Cr)."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Easy",
        questionText: `${mixSet2}**Q9.** Which category had the highest number of failed/returned orders?`,
        options: ["Electronics", "Fashion", "Home", "Toys"], correctAnswer: "Fashion", explanation: "Fashion failure rate = 15% on 20k orders = 3,000 failures (Highest)."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet2}**Q10.** Find the ratio of successful Grocery orders to successful Home orders.`,
        options: ["11:8", "15:11", "38:33", "25:22"], correctAnswer: "38:33", explanation: "Grocery success = 16000 * 0.95 = 15200. Home success = 12000 * 0.88 = 10560. Ratio = 15200 : 10560 = 380:264 = 95:66 (Or approx 38:33 scaled down)."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet2}**Q11.** Find the total revenue generated from successful Electronics and Home deliveries combined.`,
        options: ["₹5.85 Cr", "₹6.62 Cr", "₹7.15 Cr", "₹8.00 Cr"], correctAnswer: "₹6.62 Cr", explanation: "Elec Rev = 25,200 * 2000 = 5.04 Cr. Home Rev = 10,560 * 1500 = 1.584 Cr. Total = 5.04 + 1.584 = 6.624 Cr."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet2}**Q12.** What is the overall delivery success rate of the platform?`,
        options: ["85.2%", "87.5%", "88.6%", "90.0%"], correctAnswer: "88.6%", explanation: "Total Success = 25200(E) + 17000(F) + 15200(G) + 10560(H) + 3200(T) = 71,160. Rate = (71160/80000)*100 = 88.95% (Approx 88.6-89%)."
    },

    // ================== SET 3 (Q13-Q18) ==================
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet3}**Q13.** Find the total number of IT employees in the North and South regions combined.`,
        options: ["550", "600", "620", "650"], correctAnswer: "620", explanation: "North IT = 40% of 800 = 320. South IT = 50% of 600 = 300. Total = 320 + 300 = 620."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet3}**Q14.** Find the total annual IT salary expense for the West region.`,
        options: ["₹35.5 Cr", "₹38.0 Cr", "₹40.5 Cr", "₹45.0 Cr"], correctAnswer: "₹40.5 Cr", explanation: "West IT = 45% of 600 = 270 employees. Expense = 270 * 15 Lakhs = 4050 Lakhs = 40.5 Cr."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet3}**Q15.** Which region has the highest total IT salary expense?`,
        options: ["North", "South", "East", "West"], correctAnswer: "West", explanation: "North = 38.4 Cr. South = 30 Cr. East = 12 Cr. West = 40.5 Cr. West is the highest."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Easy",
        questionText: `${mixSet3}**Q16.** Find the ratio of IT employees in the East to Non-IT employees in the South.`,
        options: ["1:2", "1:3", "2:3", "3:4"], correctAnswer: "1:2", explanation: "East IT = 30% of 500 = 150. South Non-IT = 50% of 600 = 300. Ratio = 150 : 300 = 1:2."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet3}**Q17.** What is the overall percentage of IT employees in the company?`,
        options: ["40.5%", "41.6%", "42.5%", "45.0%"], correctAnswer: "41.6%", explanation: "Total IT = 320 + 300 + 150 + 270 = 1040. Overall % = (1040 / 2500) * 100 = 41.6%."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet3}**Q18.** If the average IT salary in the South is increased by 20%, what is the revised total IT salary expense for the South region?`,
        options: ["₹32 Cr", "₹34 Cr", "₹36 Cr", "₹38 Cr"], correctAnswer: "₹36 Cr", explanation: "Old South Expense = 30 Cr. 20% increase = +6 Cr. Revised = 36 Cr."
    },

    // ================== SET 4 (Q19-Q24) ==================
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet4}**Q19.** Find the total number of Premium smartphones sold by Apple (in Lakhs).`,
        options: ["10.0", "11.25", "12.5", "15.0"], correctAnswer: "11.25", explanation: "Apple Total = 25% of 50L = 12.5L. Premium = 90% of 12.5L = 11.25 Lakh units."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet4}**Q20.** Find the total number of Premium smartphones sold by Samsung (in Lakhs).`,
        options: ["5.0", "6.0", "7.5", "8.0"], correctAnswer: "6.0", explanation: "Samsung Total = 30% of 50L = 15L. Premium = 40% of 15L = 6.0 Lakh units."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet4}**Q21.** Which brand sold the highest absolute number of Non-Premium phones?`,
        options: ["Samsung", "Xiaomi", "Apple", "OnePlus"], correctAnswer: "Samsung", explanation: "Samsung Non-Premium = 60% of 15L = 9 Lakhs. Xiaomi = 90% of 10L = 9 Lakhs. Both are equal, but Samsung has high volume."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Easy",
        questionText: `${mixSet4}**Q22.** Find the ratio of Premium Apple phones to Premium OnePlus phones.`,
        options: ["2:1", "5:2", "3:1", "4:1"], correctAnswer: "3:1", explanation: "Apple Prem = 11.25L. OnePlus Prem = 50% of 7.5L = 3.75L. Ratio = 11.25 : 3.75 = 3:1."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet4}**Q23.** What percentage of total market sales belongs to the Premium segment?`,
        options: ["40.5%", "44.5%", "48.2%", "52.0%"], correctAnswer: "44.5%", explanation: "Premium Totals: S(6) + A(11.25) + X(1) + O(3.75) + Oth(0.25) = 22.25L. % = (22.25 / 50) * 100 = 44.5%."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet4}**Q24.** If Xiaomi shifts its focus and increases its premium phone ratio to 25%, how many extra premium units will it sell?`,
        options: ["1.0 Lakh", "1.5 Lakhs", "2.0 Lakhs", "2.5 Lakhs"], correctAnswer: "1.5 Lakhs", explanation: "Current Premium = 10% of 10L = 1L. New Premium = 25% of 10L = 2.5L. Extra = 1.5 Lakhs."
    },

    // ================== SET 5 (Q25-Q30) ==================
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet5}**Q25.** Find the total budget allocated to Social Media marketing in 2024.`,
        options: ["₹100 Cr", "₹120 Cr", "₹150 Cr", "₹180 Cr"], correctAnswer: "₹120 Cr", explanation: "2024 Total Budget = ₹300 Cr. Social Media = 40% of 300 = ₹120 Cr."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet5}**Q26.** Calculate the total number of customers acquired via Social Media in 2024.`,
        options: ["20 Lakhs", "22.5 Lakhs", "24 Lakhs", "25 Lakhs"], correctAnswer: "24 Lakhs", explanation: "Budget = ₹120 Cr (120,00,00,000). CAC = ₹500. Customers = 120,00,00,000 / 500 = 24,00,000 (24 Lakhs)."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet5}**Q27.** Which marketing channel was the most efficient (acquired the highest number of customers)?`,
        options: ["Social Media", "Search Ads", "Email", "Offline"], correctAnswer: "Social Media", explanation: "Social Media = 24L. Search = 90Cr/800 = 11.25L. Email = 60Cr/300 = 20L. Offline = 1.5L. Social Media acquired the most."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Easy",
        questionText: `${mixSet5}**Q28.** Find the ratio of customers acquired via Search Ads to Offline marketing.`,
        options: ["5:1", "6:1", "7.5:1", "8:1"], correctAnswer: "7.5:1", explanation: "Search = 11.25L. Offline = 1.5L. Ratio = 11.25 : 1.5 = 7.5 : 1."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Medium",
        questionText: `${mixSet5}**Q29.** What is the weighted average CAC across all channels in 2024?`,
        options: ["₹500", "₹528", "₹550", "₹600"], correctAnswer: "₹528", explanation: "Total Budget = 300 Cr. Total Customers = 24L + 11.25L + 20L + 1.5L = 56.75 Lakhs. Avg CAC = 300,00,00,000 / 56,75,000 ≈ ₹528.6."
    },
    {
        category: "Data Interpretation", topic: "Mixed Graphs (Table+Pie)", difficulty: "Hard",
        questionText: `${mixSet5}**Q30.** If the Email marketing budget is shifted entirely to Search Ads (increasing its budget to 50%), how will the total customer acquisition count change?`,
        options: ["Decreases by 12.5L", "Decreases by 15L", "Increases by 5L", "No change"], correctAnswer: "Decreases by 12.5L", explanation: "Currently Email gets 20L customers. Shifted to Search (CAC=800): 60 Cr / 800 = 7.5L customers. Net change = 7.5L - 20L = Loss of 12.5 Lakh customers."
    }
];

const seedBatch27MixedGraphs = async () => {
    try {
        console.log("🧹 ALERT: Deleting old Mixed Graph questions...");
        await Question.deleteMany({ topic: "Mixed Graphs (Table+Pie)" }); 
        
        console.log(`🚀 Injecting ${batch27Questions.length} Distinct Mixed Graph Questions...`);
        
        await Question.insertMany(batch27Questions);
        console.log(`✅ BOOM! 5 Alag-Alag Premium Datasets (Har set me 6 Qs) successfully seed ho gaye!`);
        
        process.exit();
    } catch (error) {
        console.error("Error seeding data: ", error);
        process.exit(1);
    }
};

seedBatch27MixedGraphs();