const mongoose = require('mongoose');
require('dotenv').config(); 
// Ensure this path matches your actual Model file
const Question = require('./models/Question'); 

mongoose.connect(process.env.MONGO_URI)
  .then(() => console.log('✅ MongoDB Connected for OS Module'))
  .catch(err => console.error('❌ MongoDB Connection Error:', err));

const osQuestionsBatch61to90 = [
    {
        category: "Operating System", topic: "Advanced", difficulty: "Easy",
        questionText: "**Q61.** What is the primary objective of Memory Management in an Operating System?",
        options: [
            "Increase CPU clock speed", 
            "Efficiently allocate and manage main memory among processes", 
            "Improve disk capacity", 
            "Manage network communication"
        ], 
        correctAnswer: "Efficiently allocate and manage main memory among processes",
        explanation: "Memory Management is responsible for keeping track of every byte in a system's main memory, allocating it to executing processes, and ensuring those processes do not interfere with each other."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q62.** Which memory management technique divides both logical and physical memory into fixed-size blocks?",
        options: ["Segmentation", "Paging", "Swapping", "Overlaying"], 
        correctAnswer: "Paging",
        explanation: "Paging is a memory-management scheme that eliminates the need for contiguous allocation of physical memory by dividing both logical and physical memory into identical, fixed-size blocks."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Easy",
        questionText: "**Q63.** In Paging, the fixed-size block of logical memory is called:",
        options: ["Frame", "Page", "Segment", "Block"], 
        correctAnswer: "Page",
        explanation: "In a paged memory system, the logical memory (generated by the CPU/process) is divided into fixed-size blocks called 'Pages'."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Easy",
        questionText: "**Q64.** In Paging, the fixed-size block of physical memory is called:",
        options: ["Frame", "Page", "Segment", "Cluster"], 
        correctAnswer: "Frame",
        explanation: "The physical memory (RAM) is divided into fixed-size blocks called 'Frames'. A Page from logical memory is loaded into an available Frame in physical memory."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q65.** What is the primary purpose of a Page Table?",
        options: [
            "Store file metadata", 
            "Map logical pages to physical frames", 
            "Schedule CPU processes", 
            "Manage disk sectors"
        ], 
        correctAnswer: "Map logical pages to physical frames",
        explanation: "The OS maintains a Page Table for each process. Its primary job is to translate the logical page number requested by the CPU into the actual physical frame number in RAM."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q66.** Which memory management technique divides memory into variable-sized logical units such as code, stack, and data?",
        options: ["Paging", "Segmentation", "Swapping", "Caching"], 
        correctAnswer: "Segmentation",
        explanation: "Unlike Paging which uses fixed blocks, Segmentation maps memory based on the user's view of the program, dividing it into variable-sized logical segments like main(), stack, arrays, etc."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q67.** Which statement correctly distinguishes Paging and Segmentation?",
        options: [
            "Paging uses variable-sized blocks, while Segmentation uses fixed-size blocks.", 
            "Paging eliminates external fragmentation, whereas Segmentation may suffer from external fragmentation.", 
            "Both use only fixed-size blocks.", 
            "Segmentation cannot support memory protection."
        ], 
        correctAnswer: "Paging eliminates external fragmentation, whereas Segmentation may suffer from external fragmentation.",
        explanation: "Because paging uses fixed frames, any available frame can hold any page, preventing external fragmentation. Segmentation uses variable sizes, which can leave small, unusable gaps of memory over time."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q68.** Virtual Memory allows:",
        options: [
            "Programs larger than physical memory to execute.", 
            "CPU speed to increase automatically.", 
            "Permanent storage in RAM.", 
            "Elimination of secondary storage."
        ], 
        correctAnswer: "Programs larger than physical memory to execute.",
        explanation: "Virtual Memory gives the illusion of a massive main memory by utilizing secondary storage (disk) to temporarily store parts of a process, bringing them into RAM only when actively needed."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q69.** Which hardware component is primarily used to speed up virtual-to-physical address translation?",
        options: ["ALU", "Cache Controller", "Translation Lookaside Buffer (TLB)", "DMA Controller"], 
        correctAnswer: "Translation Lookaside Buffer (TLB)",
        explanation: "The TLB is a dedicated, high-speed associative hardware cache inside the CPU that stores recent virtual-to-physical page translations to avoid slow lookups in the main memory Page Table."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q70.** A TLB Miss occurs when:",
        options: [
            "The required page is not present in main memory.", 
            "The required page-table entry is not found in the TLB.", 
            "The page is corrupted.", 
            "The CPU cache becomes full."
        ], 
        correctAnswer: "The required page-table entry is not found in the TLB.",
        explanation: "If the CPU checks the TLB and doesn't find the page translation there, it's a 'TLB Miss'. The OS must then spend extra time looking up the translation in the Page Table stored in RAM."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q71.** Which paging technique loads a page into memory only when it is actually required?",
        options: ["Static Paging", "Demand Paging", "Preemptive Paging", "Continuous Paging"], 
        correctAnswer: "Demand Paging",
        explanation: "Demand paging is a lazy-loading mechanism. Pages are only swapped from the disk into RAM when the executing process explicitly attempts to access them."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q72.** A Page Fault occurs when:",
        options: [
            "A page number exceeds the page size.", 
            "The referenced page is not currently present in physical memory.", 
            "A page contains invalid data.", 
            "The page table becomes full."
        ], 
        correctAnswer: "The referenced page is not currently present in physical memory.",
        explanation: "A Page Fault is an interrupt triggered by the hardware when a running program tries to access a memory page that is mapped in the virtual address space but not currently loaded in physical RAM."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q73.** Which page replacement algorithm always replaces the page that has not been used for the longest time in the past?",
        options: ["FIFO", "Optimal", "LRU", "Random"], 
        correctAnswer: "LRU",
        explanation: "LRU (Least Recently Used) looks backward in time and replaces the page that hasn't been accessed for the longest period, operating on the assumption that recently used pages will be used again soon."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q74.** Which page replacement algorithm replaces the page that will not be used for the longest time in the future?",
        options: ["FIFO", "LRU", "Optimal", "Clock"], 
        correctAnswer: "Optimal",
        explanation: "The Optimal Page Replacement algorithm looks forward in time and replaces the page that will not be needed for the longest time. It is theoretically perfect but practically impossible to implement since the OS cannot predict the future."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q75.** Which page replacement algorithm may suffer from Belady's Anomaly?",
        options: ["FIFO", "LRU", "Optimal", "LFU"], 
        correctAnswer: "FIFO",
        explanation: "Belady's Anomaly is a counter-intuitive phenomenon where allocating MORE physical memory frames to a process actually results in MORE page faults. This uniquely affects the FIFO algorithm."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q76.** What is Thrashing in an Operating System?",
        options: [
            "Continuous swapping of CPU processes", 
            "Excessive page faults causing the CPU to spend more time swapping pages than executing processes", 
            "Frequent disk formatting", 
            "Excessive context switching between threads only"
        ], 
        correctAnswer: "Excessive page faults causing the CPU to spend more time swapping pages than executing processes",
        explanation: "Thrashing occurs when memory is over-committed. The OS spends all its time handling page faults (moving data in and out of the disk) rather than doing productive CPU work, severely degrading performance."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q77.** Which of the following is the most common cause of Thrashing?",
        options: [
            "Large CPU cache", 
            "Insufficient physical memory for the active working set of processes", 
            "High disk capacity", 
            "Too few processes in memory"
        ], 
        correctAnswer: "Insufficient physical memory for the active working set of processes",
        explanation: "If the combined 'working set' (the set of pages actively being used by all running processes) is larger than the available physical RAM, the system will constantly evict and reload pages, causing thrashing."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q78.** Which technique helps prevent Thrashing by keeping only the actively used pages of a process in memory?",
        options: ["FIFO Scheduling", "Working Set Model", "Round Robin", "Segmentation"], 
        correctAnswer: "Working Set Model",
        explanation: "The Working Set Model tracks the subset of pages a process is actively using. By ensuring a process is only run if its entire working set fits in RAM, the OS effectively prevents thrashing."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Easy",
        questionText: "**Q79.** Which disk scheduling algorithm services requests strictly in the order they arrive?",
        options: ["SSTF", "SCAN", "FCFS", "C-SCAN"], 
        correctAnswer: "FCFS",
        explanation: "First-Come, First-Serve (FCFS) schedules disk requests exactly in the sequence they are received, which is simple but can result in very long, inefficient head movements."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q80.** Which disk scheduling algorithm always selects the request closest to the current head position?",
        options: ["FCFS", "SSTF", "SCAN", "LOOK"], 
        correctAnswer: "SSTF",
        explanation: "Shortest Seek Time First (SSTF) optimizes movement by always choosing the pending request that requires the least disk head movement from its current position. However, it can cause starvation for distant requests."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q81.** In the SCAN (Elevator) algorithm, the disk head:",
        options: [
            "Moves only toward higher cylinder numbers.", 
            "Services requests while moving in one direction, then reverses direction at the end.", 
            "Randomly selects requests.", 
            "Always returns to cylinder 0 after every request."
        ], 
        correctAnswer: "Services requests while moving in one direction, then reverses direction at the end.",
        explanation: "Much like a real elevator, the SCAN algorithm sweeps the disk from one end to the other, servicing requests along the way, and then reverses direction upon hitting the edge."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q82.** How does C-SCAN differ from SCAN?",
        options: [
            "C-SCAN services requests in both directions.", 
            "C-SCAN services requests in one direction only and jumps back to the beginning without servicing requests on the return.", 
            "C-SCAN is identical to SSTF.", 
            "C-SCAN always starts from cylinder 0."
        ], 
        correctAnswer: "C-SCAN services requests in one direction only and jumps back to the beginning without servicing requests on the return.",
        explanation: "Circular SCAN (C-SCAN) treats the disk as a cylinder. It scans in one direction, but when it hits the end, it immediately jumps back to the start without servicing requests, providing a more uniform wait time."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Easy",
        questionText: "**Q83.** Which file allocation method stores all file blocks in consecutive disk locations?",
        options: ["Linked Allocation", "Indexed Allocation", "Contiguous Allocation", "Chained Allocation"], 
        correctAnswer: "Contiguous Allocation",
        explanation: "Contiguous allocation requires that each file occupy a set of sequential, adjacent blocks on the disk. It is very fast for reading but suffers from severe external fragmentation."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q84.** Which file allocation method stores a pointer in each block to the next block of the same file?",
        options: ["Contiguous Allocation", "Linked Allocation", "Indexed Allocation", "Extent Allocation"], 
        correctAnswer: "Linked Allocation",
        explanation: "In Linked Allocation, files are stored as a linked list of disk blocks. Each block contains the data and a pointer to the address of the next block. It prevents external fragmentation."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q85.** Which file allocation method uses a separate index block containing pointers to all data blocks of a file?",
        options: ["Linked Allocation", "Indexed Allocation", "Contiguous Allocation", "Sequential Allocation"], 
        correctAnswer: "Indexed Allocation",
        explanation: "Indexed Allocation brings all the pointers together into a single 'index block'. When the file is accessed, the OS simply reads the index block to find where every piece of data is stored on the disk."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q86.** In UNIX/Linux file systems, an inode stores:",
        options: [
            "The actual contents of the file.", 
            "Metadata such as permissions, ownership, timestamps, and block addresses.", 
            "Only the filename.", 
            "The entire directory structure."
        ], 
        correctAnswer: "Metadata such as permissions, ownership, timestamps, and block addresses.",
        explanation: "An Index Node (inode) is a critical data structure in Linux/UNIX that stores all the metadata about a file (size, owner, permissions, pointers to disk blocks) EXCEPT for its actual filename and data."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Easy",
        questionText: "**Q87.** Which RAID level provides striping only, offering improved performance but no fault tolerance?",
        options: ["RAID 0", "RAID 1", "RAID 5", "RAID 10"], 
        correctAnswer: "RAID 0",
        explanation: "RAID 0 (Data Striping) spreads data across multiple disks to maximize read/write speed. However, because there is no redundancy, if one disk fails, all data is lost."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Medium",
        questionText: "**Q88.** Which RAID level provides mirroring, allowing the system to survive the failure of one disk without data loss?",
        options: ["RAID 0", "RAID 1", "RAID 5", "RAID 6"], 
        correctAnswer: "RAID 1",
        explanation: "RAID 1 creates an exact 1:1 mirror (copy) of data on two or more disks. It provides excellent fault tolerance because the system can seamlessly switch to the mirror if the primary disk fails."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q89.** Which RAID level uses distributed parity, balancing storage efficiency and fault tolerance?",
        options: ["RAID 0", "RAID 1", "RAID 5", "RAID 0+1"], 
        correctAnswer: "RAID 5",
        explanation: "RAID 5 stripes data across at least three disks and distributes parity blocks among them. This parity allows data to be mathematically reconstructed if any single disk fails, optimizing both space and safety."
    },
    {
        category: "Operating System", topic: "Advanced", difficulty: "Hard",
        questionText: "**Q90.** A database server requires high read performance, good write performance, and fault tolerance, even if it requires more disks. Which RAID configuration is generally the best choice?",
        options: ["RAID 0", "RAID 1", "RAID 5", "RAID 10"], 
        correctAnswer: "RAID 10",
        explanation: "RAID 10 (1+0) combines mirroring and striping. It is the gold standard for heavy databases because it provides the blazing speed of RAID 0 and the robust fault tolerance of RAID 1, though it is expensive."
    }
];

const seedOSQuestions61to90 = async () => {
    try {
        // Uncomment below to wipe the collection if you don't want to append
        // await Question.deleteMany({ category: "Operating System", topic: "Advanced" }); 
        
        console.log(`🚀 Injecting ${osQuestionsBatch61to90.length} Advanced OS Questions...`);
        await Question.insertMany(osQuestionsBatch61to90);
        
        console.log(`✅ SUCCESS! Questions 61 to 90 (Advanced OS) Seeded Successfully.`);
        process.exit();
    } catch (error) {
        console.error("❌ Error seeding OS data:", error);
        process.exit(1);
    }
};

seedOSQuestions61to90();